"""
backend/sentinel/webhook_notifier.py
--------------------------------------
PhantomNet Sentinel Layer - Webhook Alert Dispatcher

Sends webhook notifications (HTTP POST) to configured endpoints when high-severity 
(CRITICAL) playbooks are automatically generated by the Sentinel pipeline.

Includes exponential backoff retry logic.
"""

from __future__ import annotations

import logging
import threading
import time
import requests
import json
from typing import Any, Dict, Optional

logger = logging.getLogger("sentinel.webhook_notifier")


class SentinelWebhookNotifier:
    """Dispatches webhook alerts for CRITICAL severity sentinel playbooks.
    
    Reads webhook configuration from SystemConfig in the database.
    """
    
    def __init__(self) -> None:
        pass

    def _get_webhook_url(self) -> str:
        """Fetches the webhook_url from SystemConfig."""
        from database.database import SessionLocal
        from database.models import SystemConfig
        
        db = SessionLocal()
        try:
            config = db.query(SystemConfig).filter(SystemConfig.key == "webhook_url").first()
            if config and config.value:
                return config.value.strip()
            return ""
        except Exception as exc:
            logger.error("Failed to query webhook_url from SystemConfig: %s", exc)
            return ""
        finally:
            db.close()

    def should_alert(self, severity: Optional[str]) -> bool:
        """Determine whether an alert should be sent for the given severity."""
        if not severity:
            return False
        return severity.upper() == "CRITICAL"

    def build_webhook_payload(self, playbook) -> Dict[str, Any]:
        """Extract playbook details into a JSON-serializable dictionary."""
        # Use existing stix_bundle_json if available via result_dict, else default
        stix_json = None
        if hasattr(playbook, "result_dict") and isinstance(playbook.result_dict, dict):
            stix_json_str = playbook.result_dict.get("stix_bundle_json")
            if stix_json_str:
                try:
                    stix_json = json.loads(stix_json_str)
                except json.JSONDecodeError:
                    pass
                    
        return {
            "playbook_id": getattr(playbook, "playbook_id", "UNKNOWN"),
            "playbook_name": getattr(playbook, "playbook_name", "UNKNOWN"),
            "severity": getattr(playbook, "severity", "UNKNOWN"),
            "attack_type": getattr(playbook, "attack_type", "UNKNOWN"),
            "threat_score": getattr(playbook, "threat_score", 0.0),
            "source_ip": getattr(playbook, "src_ip", "UNKNOWN"),
            "technique_id": getattr(playbook, "technique_id", "UNKNOWN"),
            "technique_name": getattr(playbook, "technique_name", "UNKNOWN"),
            "summary": getattr(playbook, "llm_narrative", None) or getattr(playbook, "playbook_content", ""),
            "stix_alert": stix_json
        }

    def _send_with_retry(self, url: str, payload: Dict[str, Any], max_retries: int = 3) -> bool:
        """Sends POST request with exponential backoff."""
        headers = {"Content-Type": "application/json"}
        for attempt in range(1, max_retries + 1):
            try:
                response = requests.post(url, json=payload, headers=headers, timeout=10)
                response.raise_for_status()
                logger.info("Webhook notification sent successfully to %s on attempt %d", url, attempt)
                return True
            except requests.exceptions.RequestException as exc:
                logger.warning("Webhook notification attempt %d failed: %s", attempt, exc)
                if attempt < max_retries:
                    sleep_time = 2 ** attempt
                    logger.info("Retrying webhook in %d seconds...", sleep_time)
                    time.sleep(sleep_time)
                else:
                    logger.error("Webhook notification failed after %d attempts.", max_retries)
        return False

    def send_alert_async(self, playbook) -> None:
        """Send a webhook alert asynchronously in a background thread."""
        severity = getattr(playbook, "severity", None)
        if not self.should_alert(severity):
            return

        playbook_id_str = getattr(playbook, "playbook_id", "?")
        
        # We need to build payload before starting thread to capture state
        # in case the ORM object gets detached.
        payload = self.build_webhook_payload(playbook)

        def _dispatch():
            url = self._get_webhook_url()
            if not url:
                logger.info("Webhook alert skipped: no webhook_url configured in SystemConfig.")
                return

            try:
                success = self._send_with_retry(url, payload)
                if success:
                    logger.info("Async webhook alert dispatched for playbook %s", playbook_id_str)
                else:
                    logger.warning("Async webhook alert failed for playbook %s", playbook_id_str)
            except Exception as exc:
                logger.error("Async webhook alert error for playbook %s: %s", playbook_id_str, exc)

        thread = threading.Thread(target=_dispatch, daemon=True)
        thread.start()
        logger.info(
            "Webhook alert thread started for playbook %s (severity=%s)",
            playbook_id_str, severity
        )


# Module-level singleton (lazy-initialized)
_notifier_instance: Optional[SentinelWebhookNotifier] = None
_notifier_lock = threading.Lock()


def get_webhook_notifier() -> SentinelWebhookNotifier:
    """Return the module-level SentinelWebhookNotifier singleton."""
    global _notifier_instance
    if _notifier_instance is None:
        with _notifier_lock:
            if _notifier_instance is None:
                _notifier_instance = SentinelWebhookNotifier()
    return _notifier_instance


def trigger_webhook_alert_async(playbook) -> None:
    """Convenience function: trigger an async webhook alert for a playbook.

    Called from SentinelService.generate_playbook() after successful
    DB persistence. Only sends if severity is CRITICAL.
    """
    try:
        notifier = get_webhook_notifier()
        notifier.send_alert_async(playbook)
    except Exception as exc:
        logger.warning(
            "Failed to trigger webhook alert for playbook %s: %s",
            getattr(playbook, "playbook_id", "?"), exc
        )
