"""
tests/test_week15_day1_snort_validation.py
==========================================
Week 15 Day 1 — Comprehensive Snort Rule Syntax Validation

Validates ALL generated Snort rules follow Snort 2.9/3.0 syntax correctly.

Tasks covered:
  1. Collect all Snort rules generated by the sentinel pipeline
  2. Verify correct semicolon placement in rule options
  3. Verify correct parentheses usage in rule body
  4. Verify proper escape characters in msg and content fields
  5. Verify SID uniqueness across all generated rules
  6. Verify classtype values match Snort standard classtypes
  7. Verify ATT&CK reference URLs are correctly formatted
  8. Document any syntax issues found and fix in rule_generator.py
"""

import os
import re
import sys
import threading
import unittest

# ── Path setup ──────────────────────────────────────────────────────────────
PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
BACKEND_DIR = os.path.join(PROJECT_ROOT, "backend")
for p in (PROJECT_ROOT, BACKEND_DIR):
    if p not in sys.path:
        sys.path.insert(0, p)

from sentinel.rule_generator import (
    SNORT_RULE_TEMPLATE,
    VALID_SNORT_CLASSTYPES,
    ATTACK_TYPE_TO_CLASSTYPE,
    escape_snort_string,
    format_mitre_url,
    generate_snort_rule,
    generate_rules_for_campaign,
    validate_ip,
    validate_port,
)


# ---------------------------------------------------------------------------
# Helper: Snort rule parser (mirrors the one in test_rule_generator.py)
# ---------------------------------------------------------------------------

def parse_snort_rule(rule_str):
    """
    Parse a Snort rule string and validate its syntax.
    Returns a dict with parsed header and options, or raises ValueError.
    """
    if not rule_str or not rule_str.strip():
        raise ValueError("Rule string is empty")
    rule_str = rule_str.strip()

    # Find parentheses
    try:
        paren_open = rule_str.index("(")
    except ValueError:
        raise ValueError("Rule options block must contain '('")
    if not rule_str.endswith(")"):
        raise ValueError("Rule options block must end with ')'")

    header_part = rule_str[:paren_open].strip()
    options_part = rule_str[paren_open + 1: -1].strip()

    # Parse header
    tokens = header_part.split()
    if len(tokens) != 7:
        raise ValueError(
            "Header must have exactly 7 tokens, got %d: %s" % (len(tokens), tokens)
        )
    action, protocol, src_ip, src_port, direction, dst_ip, dst_port = tokens
    if action != "alert":
        raise ValueError("Rule action must be alert, got %s" % action)
    if protocol.lower() not in ("tcp", "udp", "icmp", "ip"):
        raise ValueError("Invalid protocol: %s" % protocol)
    if direction not in ("->", "<>"):
        raise ValueError("Invalid direction: %s" % direction)

    # Parse options (semicolon-delimited, respecting backslash escapes)
    raw_options = []
    current = []
    i = 0
    while i < len(options_part):
        ch = options_part[i]
        if ch == ";" and (i == 0 or options_part[i - 1] != "\\"):
            raw_options.append("".join(current).strip())
            current = []
        else:
            current.append(ch)
        i += 1
    leftover = "".join(current).strip()
    if leftover:
        raise ValueError(
            "Options block missing terminating semicolon. Leftover: %r" % leftover
        )

    parsed_options = {}
    for opt in raw_options:
        if not opt:
            continue
        if ":" in opt:
            name, value = opt.split(":", 1)
            name = name.strip()
            value = value.strip()
        else:
            name = opt.strip()
            value = True
        if name in parsed_options:
            existing = parsed_options[name]
            if not isinstance(existing, list):
                parsed_options[name] = [existing]
            parsed_options[name].append(value)
        else:
            parsed_options[name] = value

    # Verify required options
    required = ("msg", "flow", "threshold", "classtype", "priority", "reference", "sid", "rev")
    for req in required:
        if req not in parsed_options:
            raise ValueError("Missing required Snort option: %r" % req)

    # Verify msg quoting
    msg_val = parsed_options["msg"]
    if not (msg_val.startswith('"') and msg_val.endswith('"')):
        raise ValueError("msg value must be enclosed in double-quotes")

    # Verify SID is valid positive integer
    try:
        sid_int = int(parsed_options["sid"])
        if sid_int <= 0:
            raise ValueError("sid must be > 0, got %d" % sid_int)
    except (ValueError, TypeError):
        raise ValueError(
            "sid is not a valid positive integer: %s" % parsed_options["sid"]
        )

    # Verify rev is valid positive integer
    try:
        rev_int = int(parsed_options["rev"])
        if rev_int <= 0:
            raise ValueError("rev must be > 0, got %d" % rev_int)
    except (ValueError, TypeError):
        raise ValueError(
            "rev is not a valid positive integer: %s" % parsed_options["rev"]
        )

    return {
        "action": action,
        "protocol": protocol,
        "src_ip": src_ip,
        "src_port": src_port,
        "direction": direction,
        "dst_ip": dst_ip,
        "dst_port": dst_port,
        "options": parsed_options,
    }


# ---------------------------------------------------------------------------
# Test data: diverse scenarios to generate many rules
# ---------------------------------------------------------------------------

ATTACK_SCENARIOS = [
    {
        "src_ip": "192.168.10.1",
        "dst_port": 22,
        "protocol": "tcp",
        "attack_desc": "SSH Brute Force Attack",
        "technique_id": "T1110",
        "classtype": "attempted-admin",
        "severity": "HIGH",
    },
    {
        "src_ip": "10.0.0.5",
        "dst_port": 80,
        "protocol": "tcp",
        "attack_desc": "SQL Injection via HTTP",
        "technique_id": "T1190",
        "classtype": "web-application-attack",
        "severity": "CRITICAL",
    },
    {
        "src_ip": "any",
        "dst_port": "any",
        "protocol": "udp",
        "attack_desc": "DNS Amplification Flood",
        "technique_id": "T1498",
        "classtype": "attempted-dos",
    },
    {
        "src_ip": "any",
        "dst_port": "any",
        "protocol": "icmp",
        "attack_desc": "ICMP Ping Sweep Reconnaissance",
        "technique_id": "T1018",
        "classtype": "attempted-recon",
    },
    {
        "src_ip": "$EXTERNAL_NET",
        "dst_port": 443,
        "protocol": "tcp",
        "attack_desc": "Exploit Public-Facing Application (HTTPS)",
        "technique_id": "T1190",
        "classtype": "web-application-attack",
    },
    {
        "src_ip": "172.16.0.0/12",
        "dst_port": 3306,
        "protocol": "tcp",
        "attack_desc": "MySQL Data Exfiltration",
        "technique_id": "T1041",
        "classtype": "successful-admin",
    },
    {
        "src_ip": "10.10.10.10",
        "dst_port": 0,
        "protocol": "tcp",
        "attack_desc": "XSS Cross-Site Scripting Attack",
        "technique_id": "T1059.007",
        "classtype": "web-application-attack",
    },
    {
        "src_ip": "any",
        "dst_port": 0,
        "protocol": "ip",
        "attack_desc": "Generic Network Scan",
        "technique_id": "T1046",
        "classtype": "network-scan",
    },
]

# Attack descriptions with special characters for escape testing
SPECIAL_CHAR_DESCS = [
    'End; payload; drop',
    'Path\\to\\evil\\file',
    'Desc "quoted value" here',
    'Mixed; "quotes" and \\backslash',
    'Semi;colon;heavy;payload;injection',
    'Normal description without specials',
    'Alert: possible C2 channel (suspicious)',
    'PhantomNet: T1190 Exploit Public-Facing App',
]

# MITRE technique IDs in various formats
MITRE_TECHNIQUE_INPUTS = [
    ("T1190", "T1190/"),
    ("T1110.001", "T1110/001/"),
    ("T1059.007", "T1059/007/"),
    ("T1046", "T1046/"),
    ("https://attack.mitre.org/techniques/T1190/", "T1190/"),
    ("https://attack.mitre.org/techniques/T1110/001/", "T1110/001/"),
    ("https://attack.mitre.org/techniques/T1059/001/", "T1059/001/"),
]

CAMPAIGN_CLUSTERS = [
    {
        "campaign_id": "CAMP-SQLI-001",
        "cluster_id": 1,
        "unique_sources": ["203.0.113.42"],
        "target_ports": [8080],
        "protocols": ["tcp"],
        "attack_type": "sqli_attempt",
    },
    {
        "campaign_id": "CAMP-BRUTE-002",
        "cluster_id": 2,
        "unique_sources": ["10.0.0.5", "10.0.0.6"],
        "target_ports": [22, 2222],
        "protocols": ["tcp"],
        "attack_type": "brute_force",
    },
    {
        "campaign_id": "CAMP-SCAN-003",
        "cluster_id": 3,
        "unique_sources": ["192.168.1.100"],
        "target_ports": [80, 443, 8080, 8443],
        "protocols": ["tcp", "udp"],
        "attack_type": "port_scan",
    },
    {
        "campaign_id": "CAMP-MULTI-004",
        "cluster_id": 4,
        "unique_sources": ["any"],
        "target_ports": [53],
        "protocols": ["udp"],
        "attack_type": "dos_attack",
    },
]

CAMPAIGN_MITRE_INFO = [
    {"technique_id": "T1190", "technique_name": "Exploit Public-Facing Application", "severity": "CRITICAL"},
    {"technique_id": "T1110", "technique_name": "Brute Force", "severity": "HIGH"},
    {"technique_id": "T1046", "technique_name": "Network Service Discovery", "severity": "MEDIUM"},
    None,  # Fallback test
]


# ===========================================================================
# TASK 1: Collect all Snort rules from the pipeline
# ===========================================================================

class TestTask1CollectAllRules(unittest.TestCase):
    """Task 1: Collect all Snort rules generated by the sentinel pipeline."""

    def setUp(self):
        """Reset SID counter for deterministic tests."""
        import sentinel.rule_generator as rg
        if hasattr(rg, "_NEXT_SID"):
            with rg._sid_lock:
                rg._NEXT_SID = 2000001
        if hasattr(rg, "_current_sid"):
            with rg._sid_lock:
                rg._current_sid = 2000000

    def test_generate_all_scenario_rules(self):
        """All 8 attack scenarios produce valid Snort rules."""
        rules = []
        for scenario in ATTACK_SCENARIOS:
            rule = generate_snort_rule(**scenario)
            self.assertIsInstance(rule, str)
            self.assertTrue(len(rule) > 50, "Rule is too short: %s" % rule)
            rules.append(rule)
        self.assertEqual(len(rules), len(ATTACK_SCENARIOS))

    def test_campaign_rules_generated_for_all_clusters(self):
        """All campaign clusters produce at least one Snort rule."""
        for i, cluster in enumerate(CAMPAIGN_CLUSTERS):
            mitre = CAMPAIGN_MITRE_INFO[i % len(CAMPAIGN_MITRE_INFO)]
            result = generate_rules_for_campaign(cluster, mitre)
            self.assertIn("snort_rules_list", result)
            self.assertGreater(
                len(result["snort_rules_list"]), 0,
                "Cluster %s produced 0 Snort rules" % cluster["campaign_id"],
            )

    def test_campaign_multi_source_multi_port_rule_count(self):
        """2 sources x 2 ports x 1 protocol x 1 technique = 4 Snort rules."""
        cluster = CAMPAIGN_CLUSTERS[1]  # BRUTE-002: 2 IPs, 2 ports, 1 proto
        mitre = CAMPAIGN_MITRE_INFO[1]  # T1110
        result = generate_rules_for_campaign(cluster, mitre)
        self.assertEqual(result["metadata"]["snort_rule_count"], 4)

    def test_collect_all_rules_from_all_campaigns(self):
        """Collect every generated rule across all campaigns — all non-empty strings."""
        all_rules = []
        for i, cluster in enumerate(CAMPAIGN_CLUSTERS):
            mitre = CAMPAIGN_MITRE_INFO[i % len(CAMPAIGN_MITRE_INFO)]
            result = generate_rules_for_campaign(cluster, mitre)
            all_rules.extend(result["snort_rules_list"])
        self.assertGreater(len(all_rules), 0, "No rules collected!")
        for rule in all_rules:
            self.assertIsInstance(rule, str)
            self.assertTrue(rule.startswith("alert"), "Rule doesn't start with alert: %s" % rule[:60])


# ===========================================================================
# TASK 2: Verify correct semicolon placement
# ===========================================================================

class TestTask2SemicolonPlacement(unittest.TestCase):
    """Task 2: Verify correct semicolon placement in rule options."""

    def _generate_test_rules(self):
        rules = []
        for scenario in ATTACK_SCENARIOS:
            rules.append(generate_snort_rule(**scenario))
        return rules

    def test_every_option_ends_with_semicolon(self):
        """Every option in the options block ends with a semicolon."""
        for rule in self._generate_test_rules():
            options_region = rule[rule.index("(") + 1: -1].strip()
            self.assertTrue(
                options_region.endswith(";"),
                "Options block doesn't end with ';': ...%s" % options_region[-30:],
            )

    def test_msg_option_semicolon_terminated(self):
        """msg option is properly semicolon-terminated (not inside quotes)."""
        for rule in self._generate_test_rules():
            # After msg:"..."; there must be a semicolon after the closing quote
            self.assertRegex(rule, r'msg:"[^"]*";\s')

    def test_sid_option_semicolon_terminated(self):
        """sid:NNNN; option is properly semicolon-terminated."""
        for rule in self._generate_test_rules():
            self.assertRegex(rule, r"sid:\d+;")

    def test_rev_option_semicolon_terminated(self):
        """rev:N; option is properly semicolon-terminated."""
        for rule in self._generate_test_rules():
            self.assertRegex(rule, r"rev:\d+;")

    def test_classtype_option_semicolon_terminated(self):
        """classtype:value; option is properly semicolon-terminated."""
        for rule in self._generate_test_rules():
            self.assertRegex(rule, r"classtype:[a-z\-]+;")

    def test_flow_option_semicolon_terminated(self):
        """flow:to_server,established; is properly semicolon-terminated."""
        for rule in self._generate_test_rules():
            self.assertIn("flow:to_server,established;", rule)

    def test_reference_option_semicolon_terminated(self):
        """reference:url,...; is properly semicolon-terminated."""
        for rule in self._generate_test_rules():
            self.assertRegex(rule, r"reference:url,[^;]+;")

    def test_threshold_option_semicolon_terminated(self):
        """threshold option is properly semicolon-terminated."""
        for rule in self._generate_test_rules():
            self.assertIn("seconds 60;", rule)

    def test_no_double_semicolons(self):
        """No unescaped double semicolons ;; in any rule."""
        for rule in self._generate_test_rules():
            # Strip escaped semicolons first, then check
            cleaned = rule.replace("\\;", "")
            self.assertNotIn(";;", cleaned,
                             "Double semicolons found in: %s" % rule[:80])

    def test_campaign_rules_semicolon_placement(self):
        """Campaign-generated rules have correct semicolon placement."""
        for i, cluster in enumerate(CAMPAIGN_CLUSTERS):
            mitre = CAMPAIGN_MITRE_INFO[i % len(CAMPAIGN_MITRE_INFO)]
            result = generate_rules_for_campaign(cluster, mitre)
            for rule in result["snort_rules_list"]:
                options_region = rule[rule.index("(") + 1: -1].strip()
                self.assertTrue(
                    options_region.endswith(";"),
                    "Campaign rule options not ';' terminated: %s" % rule[:60],
                )


# ===========================================================================
# TASK 3: Verify correct parentheses usage
# ===========================================================================

class TestTask3ParenthesesUsage(unittest.TestCase):
    """Task 3: Verify correct parentheses usage in rule body."""

    def _generate_test_rules(self):
        rules = []
        for scenario in ATTACK_SCENARIOS:
            rules.append(generate_snort_rule(**scenario))
        return rules

    def test_rule_has_opening_parenthesis(self):
        """Every rule has an opening parenthesis."""
        for rule in self._generate_test_rules():
            self.assertIn("(", rule)

    def test_rule_ends_with_closing_parenthesis(self):
        """Every rule ends with a closing parenthesis."""
        for rule in self._generate_test_rules():
            self.assertTrue(rule.strip().endswith(")"))

    def test_balanced_parentheses(self):
        """Parentheses are balanced in every rule."""
        for rule in self._generate_test_rules():
            open_count = rule.count("(")
            close_count = rule.count(")")
            self.assertEqual(
                open_count, close_count,
                "Unbalanced parentheses (%d open, %d close) in: %s"
                % (open_count, close_count, rule[:80]),
            )

    def test_options_block_inside_parentheses(self):
        """Options block is entirely enclosed between ( and )."""
        for rule in self._generate_test_rules():
            paren_open = rule.index("(")
            self.assertTrue(rule.endswith(")"))
            options = rule[paren_open + 1: -1].strip()
            self.assertIn("msg:", options)
            self.assertIn("sid:", options)

    def test_header_before_parentheses(self):
        """Rule header (alert proto src ...) comes before the opening parenthesis."""
        for rule in self._generate_test_rules():
            paren_open = rule.index("(")
            header = rule[:paren_open].strip()
            self.assertTrue(header.startswith("alert"))
            tokens = header.split()
            self.assertEqual(len(tokens), 7, "Header has wrong token count: %s" % header)

    def test_campaign_rules_parentheses(self):
        """Campaign-generated rules have correct parentheses usage."""
        for i, cluster in enumerate(CAMPAIGN_CLUSTERS):
            mitre = CAMPAIGN_MITRE_INFO[i % len(CAMPAIGN_MITRE_INFO)]
            result = generate_rules_for_campaign(cluster, mitre)
            for rule in result["snort_rules_list"]:
                self.assertIn("(", rule)
                self.assertTrue(rule.strip().endswith(")"))
                self.assertEqual(rule.count("("), rule.count(")"))

    def test_parseable_by_snort_parser(self):
        """Every generated rule is parseable by the Snort rule parser."""
        for rule in self._generate_test_rules():
            try:
                parsed = parse_snort_rule(rule)
                self.assertIsNotNone(parsed)
            except ValueError as e:
                self.fail("Rule failed to parse: %s\nError: %s" % (rule[:80], e))


# ===========================================================================
# TASK 4: Verify proper escape characters
# ===========================================================================

class TestTask4EscapeCharacters(unittest.TestCase):
    """Task 4: Verify proper escape characters in msg and content fields."""

    def test_semicolon_in_msg_is_escaped(self):
        """Semicolons inside msg are escaped as \\;"""
        rule = generate_snort_rule(
            "any", 80, "tcp", "End; payload; here", "T1190"
        )
        parsed = parse_snort_rule(rule)
        msg = parsed["options"]["msg"]
        self.assertIn("\\;", msg)

    def test_backslash_in_msg_is_doubled(self):
        """Backslashes inside msg are doubled \\\\."""
        rule = generate_snort_rule(
            "any", 80, "tcp", "Path\\to\\evil", "T1190"
        )
        parsed = parse_snort_rule(rule)
        msg = parsed["options"]["msg"]
        self.assertIn("\\\\", msg)

    def test_double_quote_in_msg_is_escaped(self):
        """Double-quotes inside msg are escaped as \\\"."""
        rule = generate_snort_rule(
            "any", 80, "tcp", 'Desc "quoted" value', "T1190"
        )
        parsed = parse_snort_rule(rule)
        msg = parsed["options"]["msg"]
        self.assertIn('\\"', msg)

    def test_combined_special_chars_in_msg(self):
        """Combined special characters are all properly escaped."""
        rule = generate_snort_rule(
            "any", 80, "tcp", 'Mixed; "quotes" and \\backslash', "T1190"
        )
        parsed = parse_snort_rule(rule)
        msg = parsed["options"]["msg"]
        self.assertIn("\\;", msg)
        self.assertIn('\\"', msg)
        self.assertIn("\\\\", msg)

    def test_all_special_descs_produce_parseable_rules(self):
        """All special character descriptions produce parseable Snort rules."""
        for desc in SPECIAL_CHAR_DESCS:
            rule = generate_snort_rule("any", 80, "tcp", desc, "T1190")
            try:
                parsed = parse_snort_rule(rule)
                self.assertIsNotNone(parsed)
            except ValueError as e:
                self.fail(
                    "Rule with desc %r failed to parse: %s" % (desc, e)
                )

    def test_escaped_semicolons_dont_terminate_msg_option(self):
        """Escaped semicolons inside msg don't split the option."""
        rule = generate_snort_rule(
            "any", 80, "tcp", "Semi;colon;heavy;payload", "T1190"
        )
        parsed = parse_snort_rule(rule)
        msg = parsed["options"]["msg"]
        # The entire description should be in one msg value
        self.assertIn("Semi", msg)
        self.assertIn("payload", msg)

    def test_msg_starts_and_ends_with_double_quotes(self):
        """Every generated rule's msg field starts and ends with double quotes."""
        for scenario in ATTACK_SCENARIOS:
            rule = generate_snort_rule(**scenario)
            parsed = parse_snort_rule(rule)
            msg = parsed["options"]["msg"]
            self.assertTrue(msg.startswith('"'), "msg doesn't start with quote: %s" % msg)
            self.assertTrue(msg.endswith('"'), "msg doesn't end with quote: %s" % msg)

    def test_escape_snort_string_empty_input(self):
        """escape_snort_string handles non-string input gracefully."""
        self.assertEqual(escape_snort_string(None), "")
        self.assertEqual(escape_snort_string(123), "")
        self.assertEqual(escape_snort_string(""), "")

    def test_escape_snort_string_no_specials(self):
        """Strings without special chars pass through unchanged."""
        self.assertEqual(escape_snort_string("normal text"), "normal text")

    def test_campaign_rules_msg_properly_escaped(self):
        """Campaign rules with special characters in descriptions have valid msg fields."""
        cluster = {
            "campaign_id": "CAMP-ESCAPE",
            "unique_sources": ["1.2.3.4"],
            "target_ports": [80],
            "protocols": ["tcp"],
        }
        mitre = {
            "technique_id": "T1190",
            "technique_name": 'Exploit; "Public-Facing" App\\Path',
            "severity": "HIGH",
        }
        result = generate_rules_for_campaign(cluster, mitre)
        for rule in result["snort_rules_list"]:
            parsed = parse_snort_rule(rule)
            self.assertIsNotNone(parsed)


# ===========================================================================
# TASK 5: Verify SID uniqueness across all generated rules
# ===========================================================================

class TestTask5SIDUniqueness(unittest.TestCase):
    """Task 5: Verify SID uniqueness across all generated rules."""

    def setUp(self):
        """Reset SID counter for deterministic tests."""
        import sentinel.rule_generator as rg
        from sentinel.rule_generator import _SID_FILE_PATH

        self._original_exists = os.path.exists(_SID_FILE_PATH)
        self._original_val = None
        if self._original_exists:
            try:
                with open(_SID_FILE_PATH, "r") as f:
                    self._original_val = f.read()
            except Exception:
                pass

        if os.path.exists(_SID_FILE_PATH):
            try:
                os.remove(_SID_FILE_PATH)
            except Exception:
                pass

        if hasattr(rg, "_NEXT_SID"):
            with rg._sid_lock:
                rg._NEXT_SID = 3000001
        if hasattr(rg, "_current_sid"):
            with rg._sid_lock:
                rg._current_sid = 3000000

    def tearDown(self):
        import sentinel.rule_generator as rg
        from sentinel.rule_generator import _SID_FILE_PATH

        if self._original_exists and self._original_val is not None:
            try:
                os.makedirs(os.path.dirname(_SID_FILE_PATH), exist_ok=True)
                with open(_SID_FILE_PATH, "w") as f:
                    f.write(self._original_val)
                if hasattr(rg, "_NEXT_SID"):
                    with rg._sid_lock:
                        rg._NEXT_SID = rg._load_sid()
                if hasattr(rg, "_current_sid"):
                    with rg._sid_lock:
                        rg._current_sid = rg._load_sid() - 1
            except Exception:
                pass
        elif os.path.exists(_SID_FILE_PATH):
            try:
                os.remove(_SID_FILE_PATH)
            except Exception:
                pass

    def _extract_sid(self, rule_str):
        m = re.search(r"sid:(\d+);", rule_str)
        return int(m.group(1)) if m else None

    def test_all_scenario_rules_have_unique_sids(self):
        """All 8 scenario rules have unique SIDs."""
        sids = []
        for scenario in ATTACK_SCENARIOS:
            rule = generate_snort_rule(**scenario)
            sid = self._extract_sid(rule)
            self.assertIsNotNone(sid, "No SID found in rule")
            sids.append(sid)
        self.assertEqual(len(sids), len(set(sids)),
                         "Duplicate SIDs: %s" % sorted(sids))

    def test_50_sequential_sids_unique(self):
        """50 sequential auto-SID calls produce 50 unique SIDs."""
        sids = []
        for _ in range(50):
            rule = generate_snort_rule("any", 80, "tcp", "SID test", "T1234")
            sids.append(self._extract_sid(rule))
        self.assertEqual(len(sids), len(set(sids)))

    def test_sids_are_strictly_increasing(self):
        """Sequential SIDs are strictly increasing."""
        sids = []
        for _ in range(20):
            rule = generate_snort_rule("any", 80, "tcp", "SID test", "T1234")
            sids.append(self._extract_sid(rule))
        for a, b in zip(sids, sids[1:]):
            self.assertLess(a, b, "SIDs not increasing: %d >= %d" % (a, b))

    def test_campaign_rules_have_unique_sids(self):
        """All rules across all campaigns have unique SIDs."""
        all_sids = []
        for i, cluster in enumerate(CAMPAIGN_CLUSTERS):
            mitre = CAMPAIGN_MITRE_INFO[i % len(CAMPAIGN_MITRE_INFO)]
            result = generate_rules_for_campaign(cluster, mitre)
            for rule in result["snort_rules_list"]:
                sid = self._extract_sid(rule)
                self.assertIsNotNone(sid)
                all_sids.append(sid)
        self.assertGreater(len(all_sids), 0, "No SIDs collected")
        self.assertEqual(len(all_sids), len(set(all_sids)),
                         "Duplicate SIDs across campaigns: %s" % sorted(all_sids))

    def test_concurrent_sids_unique(self):
        """20 concurrent threads produce 20 unique SIDs."""
        results = []
        lock = threading.Lock()
        errors = []

        def worker():
            try:
                rule = generate_snort_rule("any", 80, "tcp", "concurrent", "T1234")
                sid = self._extract_sid(rule)
                with lock:
                    results.append(sid)
            except Exception as e:
                with lock:
                    errors.append(str(e))

        threads = [threading.Thread(target=worker) for _ in range(20)]
        for t in threads:
            t.start()
        for t in threads:
            t.join()

        self.assertFalse(errors, "Errors in threads: %s" % errors)
        self.assertEqual(len(results), len(set(results)),
                         "Duplicate concurrent SIDs: %s" % sorted(results))

    def test_all_sids_are_positive(self):
        """Every generated SID is a positive integer >= 1."""
        for scenario in ATTACK_SCENARIOS:
            rule = generate_snort_rule(**scenario)
            sid = self._extract_sid(rule)
            self.assertIsNotNone(sid)
            self.assertGreater(sid, 0, "SID must be positive, got %d" % sid)

    def test_explicit_sid_prevents_collision(self):
        """Explicit high SID advances counter to prevent future collisions."""
        high = 7_000_000
        generate_snort_rule("any", 80, "tcp", "explicit", "T1234", sid=high)
        next_rule = generate_snort_rule("any", 80, "tcp", "next auto", "T1234")
        next_sid = self._extract_sid(next_rule)
        self.assertEqual(next_sid, high + 1)


# ===========================================================================
# TASK 6: Verify classtype values match Snort standard
# ===========================================================================

class TestTask6ClasstypeValidation(unittest.TestCase):
    """Task 6: Verify classtype values match Snort standard classtypes."""

    def test_valid_classtypes_set_is_comprehensive(self):
        """VALID_SNORT_CLASSTYPES contains at least 30 standard entries."""
        self.assertGreaterEqual(len(VALID_SNORT_CLASSTYPES), 30)

    def test_common_classtypes_present(self):
        """Most commonly used Snort classtypes are in the valid set."""
        common = [
            "attempted-admin", "attempted-dos", "attempted-recon",
            "web-application-attack", "trojan-activity", "network-scan",
            "shellcode-detect", "misc-attack", "policy-violation",
        ]
        for ct in common:
            self.assertIn(ct, VALID_SNORT_CLASSTYPES,
                          "%s not in VALID_SNORT_CLASSTYPES" % ct)

    def test_attack_type_to_classtype_mapping_values_are_valid(self):
        """Every value in ATTACK_TYPE_TO_CLASSTYPE is a valid Snort classtype."""
        for attack_type, classtype in ATTACK_TYPE_TO_CLASSTYPE.items():
            self.assertIn(
                classtype, VALID_SNORT_CLASSTYPES,
                "Attack type %r maps to invalid classtype %r" % (attack_type, classtype),
            )

    def test_sqli_maps_to_web_application_attack(self):
        """SQL injection attack types map to web-application-attack classtype."""
        self.assertEqual(ATTACK_TYPE_TO_CLASSTYPE["sqli_attempt"], "web-application-attack")
        self.assertEqual(ATTACK_TYPE_TO_CLASSTYPE["sql_injection"], "web-application-attack")

    def test_brute_force_maps_to_attempted_admin(self):
        """Brute force attack types map to attempted-admin classtype."""
        self.assertEqual(ATTACK_TYPE_TO_CLASSTYPE["brute_force"], "attempted-admin")

    def test_port_scan_maps_to_attempted_recon(self):
        """Port scan maps to attempted-recon classtype."""
        self.assertEqual(ATTACK_TYPE_TO_CLASSTYPE["port_scan"], "attempted-recon")

    def test_dos_maps_to_attempted_dos(self):
        """DoS attack maps to attempted-dos classtype."""
        self.assertEqual(ATTACK_TYPE_TO_CLASSTYPE["dos_attack"], "attempted-dos")

    def test_generated_rule_uses_specified_classtype(self):
        """generate_snort_rule honours the classtype parameter."""
        rule = generate_snort_rule(
            "any", 80, "tcp", "Test", "T1190",
            classtype="web-application-attack",
        )
        parsed = parse_snort_rule(rule)
        self.assertEqual(parsed["options"]["classtype"], "web-application-attack")

    def test_default_classtype_is_attempted_admin(self):
        """Default classtype (no parameter) is attempted-admin."""
        rule = generate_snort_rule("any", 80, "tcp", "Default CT", "T1234")
        parsed = parse_snort_rule(rule)
        self.assertEqual(parsed["options"]["classtype"], "attempted-admin")

    def test_invalid_classtype_raises_valueerror(self):
        """Invalid classtype raises ValueError."""
        result = generate_snort_rule(
                "any", 80, "tcp", "Test", "T1234",
                classtype="not-a-real-classtype",
            )

        self.assertIsInstance(result, dict)

        self.assertEqual(result.get('status'), 'error')

    def test_all_scenario_rules_have_valid_classtypes(self):
        """Every scenario rule uses a classtype from the valid set."""
        for scenario in ATTACK_SCENARIOS:
            rule = generate_snort_rule(**scenario)
            parsed = parse_snort_rule(rule)
            ct = parsed["options"]["classtype"]
            self.assertIn(
                ct, VALID_SNORT_CLASSTYPES,
                "Rule has invalid classtype %r" % ct,
            )

    def test_campaign_rules_have_valid_classtypes(self):
        """Every campaign-generated rule uses a valid classtype."""
        for i, cluster in enumerate(CAMPAIGN_CLUSTERS):
            mitre = CAMPAIGN_MITRE_INFO[i % len(CAMPAIGN_MITRE_INFO)]
            result = generate_rules_for_campaign(cluster, mitre)
            for rule in result["snort_rules_list"]:
                parsed = parse_snort_rule(rule)
                ct = parsed["options"]["classtype"]
                self.assertIn(
                    ct, VALID_SNORT_CLASSTYPES,
                    "Campaign rule has invalid classtype %r: %s"
                    % (ct, rule[:60]),
                )

    def test_classtype_case_insensitive_acceptance(self):
        """Classtype parameter accepts mixed-case input and normalises it."""
        rule = generate_snort_rule(
            "any", 80, "tcp", "Case test", "T1234",
            classtype="Attempted-Admin",
        )
        parsed = parse_snort_rule(rule)
        self.assertEqual(parsed["options"]["classtype"], "attempted-admin")

    def test_template_has_classtype_placeholder(self):
        """SNORT_RULE_TEMPLATE uses {classtype} placeholder."""
        self.assertIn("{classtype}", SNORT_RULE_TEMPLATE)


# ===========================================================================
# TASK 7: Verify ATT&CK reference URLs
# ===========================================================================

class TestTask7ATTCKReferenceURLs(unittest.TestCase):
    """Task 7: Verify ATT&CK reference URLs are correctly formatted."""

    def test_format_mitre_url_plain_technique(self):
        """Plain technique ID formats to 'TNNNN/'."""
        self.assertEqual(format_mitre_url("T1190"), "T1190/")

    def test_format_mitre_url_sub_technique(self):
        """Sub-technique formats to 'TNNNN/NNN/'."""
        self.assertEqual(format_mitre_url("T1110.001"), "T1110/001/")

    def test_format_mitre_url_full_url(self):
        """Full ATT&CK URL extracts to 'TNNNN/' or 'TNNNN/NNN/'."""
        for input_val, expected in MITRE_TECHNIQUE_INPUTS:
            with self.subTest(input=input_val):
                self.assertEqual(format_mitre_url(input_val), expected)

    def test_format_mitre_url_empty_returns_empty(self):
        """Empty/None input returns empty string."""
        self.assertEqual(format_mitre_url(""), "")
        self.assertEqual(format_mitre_url(None), "")

    def test_reference_field_format_in_generated_rule(self):
        """Reference field in generated rules follows 'url,attack.mitre.org/techniques/...' format."""
        for input_val, expected in MITRE_TECHNIQUE_INPUTS:
            rule = generate_snort_rule("any", 80, "tcp", "Ref test", input_val)
            parsed = parse_snort_rule(rule)
            ref = parsed["options"]["reference"]
            expected_ref = "url,attack.mitre.org/techniques/%s" % expected
            self.assertEqual(
                ref, expected_ref,
                "Reference mismatch for input %r: got %r, expected %r"
                % (input_val, ref, expected_ref),
            )

    def test_reference_url_has_trailing_slash(self):
        """ATT&CK reference URL path always ends with a trailing slash."""
        for scenario in ATTACK_SCENARIOS:
            rule = generate_snort_rule(**scenario)
            parsed = parse_snort_rule(rule)
            ref = parsed["options"]["reference"]
            # Extract the path portion after techniques/
            path = ref.split("techniques/")[1] if "techniques/" in ref else ""
            self.assertTrue(
                path.endswith("/"),
                "Reference path missing trailing slash: %s" % ref,
            )

    def test_reference_contains_attack_mitre_org(self):
        """All generated rules reference attack.mitre.org."""
        for scenario in ATTACK_SCENARIOS:
            rule = generate_snort_rule(**scenario)
            self.assertIn("attack.mitre.org/techniques/", rule)

    def test_campaign_rules_have_valid_references(self):
        """Campaign rules have properly formatted ATT&CK references."""
        for i, cluster in enumerate(CAMPAIGN_CLUSTERS):
            mitre = CAMPAIGN_MITRE_INFO[i % len(CAMPAIGN_MITRE_INFO)]
            result = generate_rules_for_campaign(cluster, mitre)
            for rule in result["snort_rules_list"]:
                parsed = parse_snort_rule(rule)
                ref = parsed["options"]["reference"]
                self.assertTrue(
                    ref.startswith("url,attack.mitre.org/techniques/"),
                    "Invalid reference format: %s" % ref,
                )
                path = ref.split("techniques/")[1]
                self.assertTrue(
                    path.endswith("/"),
                    "Reference path missing trailing slash: %s" % ref,
                )

    def test_sub_technique_reference_dot_to_slash(self):
        """Sub-technique T1110.001 becomes T1110/001/ in the reference."""
        rule = generate_snort_rule(
            "any", 80, "tcp", "Sub-technique", "T1110.001"
        )
        self.assertIn("T1110/001/", rule)
        self.assertNotIn("T1110.001", rule)  # dot notation must be converted


# ===========================================================================
# Integration: Full rule-set syntax validation
# ===========================================================================

class TestIntegrationFullRuleSetValidation(unittest.TestCase):
    """Integration: Validate every rule from every source passes full parse."""

    def setUp(self):
        """Reset SID counter."""
        import sentinel.rule_generator as rg
        if hasattr(rg, "_NEXT_SID"):
            with rg._sid_lock:
                rg._NEXT_SID = 5000001
        if hasattr(rg, "_current_sid"):
            with rg._sid_lock:
                rg._current_sid = 5000000

    def test_all_individual_scenario_rules_parse(self):
        """Every individual scenario rule passes full syntax parse."""
        for scenario in ATTACK_SCENARIOS:
            rule = generate_snort_rule(**scenario)
            with self.subTest(desc=scenario["attack_desc"]):
                parsed = parse_snort_rule(rule)
                self.assertEqual(parsed["action"], "alert")
                self.assertIn(parsed["protocol"], ("tcp", "udp", "icmp", "ip"))
                self.assertIn(parsed["options"]["classtype"], VALID_SNORT_CLASSTYPES)

    def test_all_campaign_rules_parse(self):
        """Every campaign rule passes full syntax parse."""
        for i, cluster in enumerate(CAMPAIGN_CLUSTERS):
            mitre = CAMPAIGN_MITRE_INFO[i % len(CAMPAIGN_MITRE_INFO)]
            result = generate_rules_for_campaign(cluster, mitre)
            for rule in result["snort_rules_list"]:
                with self.subTest(rule=rule[:60]):
                    parsed = parse_snort_rule(rule)
                    self.assertEqual(parsed["action"], "alert")

    def test_all_special_char_rules_parse(self):
        """All rules with special character descriptions parse correctly."""
        for desc in SPECIAL_CHAR_DESCS:
            rule = generate_snort_rule("any", 80, "tcp", desc, "T1190")
            with self.subTest(desc=desc):
                parsed = parse_snort_rule(rule)
                self.assertEqual(parsed["action"], "alert")

    def test_all_protocol_variants(self):
        """Rules with all 4 valid protocols (tcp, udp, icmp, ip) parse correctly."""
        for proto in ("tcp", "udp", "icmp", "ip"):
            rule = generate_snort_rule(
                "any", "any", proto, "Protocol %s test" % proto, "T1046"
            )
            with self.subTest(protocol=proto):
                parsed = parse_snort_rule(rule)
                self.assertEqual(parsed["protocol"], proto)

    def test_total_generated_rules_count(self):
        """Verify we generate a substantial number of rules for validation."""
        total = 0
        for scenario in ATTACK_SCENARIOS:
            generate_snort_rule(**scenario)
            total += 1
        for i, cluster in enumerate(CAMPAIGN_CLUSTERS):
            mitre = CAMPAIGN_MITRE_INFO[i % len(CAMPAIGN_MITRE_INFO)]
            result = generate_rules_for_campaign(cluster, mitre)
            total += len(result["snort_rules_list"])
        self.assertGreater(total, 15, "Expected > 15 total rules, got %d" % total)


if __name__ == "__main__":
    unittest.main(verbosity=2)
