"""
Tests for the Sentinel Webhook Notifier
"""
import json
import pytest
from unittest.mock import patch, MagicMock

from backend.sentinel.webhook_notifier import SentinelWebhookNotifier, get_webhook_notifier

class MockPlaybook:
    def __init__(self):
        self.playbook_id = "PB-12345"
        self.playbook_name = "Test Playbook"
        self.severity = "CRITICAL"
        self.attack_type = "SSH Brute Force"
        self.threat_score = 85.5
        self.src_ip = "192.168.1.100"
        self.technique_id = "T1110"
        self.technique_name = "Brute Force"
        self.llm_narrative = "This is a summary generated by LLM."
        self.playbook_content = "Fallback content"
        self.result_dict = {
            "stix_bundle_json": '{"type": "bundle", "id": "bundle--123"}'
        }

def test_should_alert():
    notifier = SentinelWebhookNotifier()
    assert notifier.should_alert("CRITICAL") is True
    assert notifier.should_alert("critical") is True
    assert notifier.should_alert("HIGH") is False
    assert notifier.should_alert("MEDIUM") is False
    assert notifier.should_alert("LOW") is False
    assert notifier.should_alert(None) is False

def test_build_webhook_payload():
    notifier = SentinelWebhookNotifier()
    playbook = MockPlaybook()
    
    payload = notifier.build_webhook_payload(playbook)
    
    assert payload["playbook_id"] == "PB-12345"
    assert payload["severity"] == "CRITICAL"
    assert payload["summary"] == "This is a summary generated by LLM."
    assert payload["stix_alert"]["type"] == "bundle"
    assert payload["stix_alert"]["id"] == "bundle--123"

def test_build_webhook_payload_fallback_summary():
    notifier = SentinelWebhookNotifier()
    playbook = MockPlaybook()
    playbook.llm_narrative = None  # Force fallback to playbook_content
    
    payload = notifier.build_webhook_payload(playbook)
    assert payload["summary"] == "Fallback content"

@patch('backend.sentinel.webhook_notifier.SentinelWebhookNotifier.validate_webhook_url')
@patch('backend.sentinel.webhook_notifier.requests.post')
def test_send_with_retry_success(mock_post, mock_validate):
    notifier = SentinelWebhookNotifier()
    
    # Mock a successful response
    mock_response = MagicMock()
    mock_response.raise_for_status.return_value = None
    mock_post.return_value = mock_response
    
    payload = {"test": "data"}
    result = notifier._send_with_retry("http://test.local", payload)
    
    assert result is True
    assert mock_post.call_count == 1
    mock_post.assert_called_once_with(
        "http://test.local", 
        json=payload, 
        headers={"Content-Type": "application/json"}, 
        timeout=10
    )

@patch('backend.sentinel.webhook_notifier.SentinelWebhookNotifier.validate_webhook_url')
@patch('backend.sentinel.webhook_notifier.time.sleep')
@patch('backend.sentinel.webhook_notifier.requests.post')
def test_send_with_retry_failure_then_success(mock_post, mock_sleep, mock_validate):
    notifier = SentinelWebhookNotifier()
    
    import requests
    # Mock first call raises exception, second call succeeds
    error = requests.exceptions.RequestException("Connection error")
    mock_response = MagicMock()
    mock_response.raise_for_status.return_value = None
    mock_post.side_effect = [error, mock_response]
    
    payload = {"test": "data"}
    result = notifier._send_with_retry("http://test.local", payload, max_retries=3)
    
    assert result is True
    assert mock_post.call_count == 2
    mock_sleep.assert_called_once_with(2)  # 2^1 sleep on first failure

@patch('backend.sentinel.webhook_notifier.SentinelWebhookNotifier.validate_webhook_url')
@patch('backend.sentinel.webhook_notifier.time.sleep')
@patch('backend.sentinel.webhook_notifier.requests.post')
def test_send_with_retry_all_failures(mock_post, mock_sleep, mock_validate):
    notifier = SentinelWebhookNotifier()
    
    import requests
    error = requests.exceptions.RequestException("Connection error")
    mock_post.side_effect = [error, error, error]
    
    payload = {"test": "data"}
    result = notifier._send_with_retry("http://test.local", payload, max_retries=3)
    
    assert result is False
    assert mock_post.call_count == 3
    assert mock_sleep.call_count == 2  # Sleeps on attempt 1 and 2, but not 3

@patch.object(SentinelWebhookNotifier, '_get_webhook_url')
@patch.object(SentinelWebhookNotifier, '_send_with_retry')
def test_send_alert_async(mock_send, mock_get_url):
    notifier = SentinelWebhookNotifier()
    mock_get_url.return_value = "http://test.local"
    mock_send.return_value = True
    
    playbook = MockPlaybook()
    notifier.send_alert_async(playbook)
    
    # Wait for the background thread to finish
    import time
    time.sleep(0.1)
    
    mock_get_url.assert_called_once()
    assert mock_send.call_count == 1
    args, _ = mock_send.call_args
    assert args[0] == "http://test.local"
    assert args[1]["playbook_id"] == "PB-12345"

@patch.object(SentinelWebhookNotifier, '_get_webhook_url')
@patch.object(SentinelWebhookNotifier, '_send_with_retry')
def test_send_alert_async_non_critical(mock_send, mock_get_url):
    notifier = SentinelWebhookNotifier()
    
    playbook = MockPlaybook()
    playbook.severity = "HIGH"  # Not CRITICAL
    
    notifier.send_alert_async(playbook)
    
    # Wait for potential thread
    import time
    time.sleep(0.1)
    
    # Should not alert
    mock_get_url.assert_not_called()
    mock_send.assert_not_called()
